### ISSUE TITLE
Any idea how to solve this error??

### ISSUE THREAD

**Issue by shabaad** [sondv301/flutter_audio_cutter#5]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.arthenica.ffmpegkit.Abi found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1) and jetified-ffmpeg-kit-min-gpl-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-min-gpl:4.5.1-1)
Duplicate class com.arthenica.ffmpegkit.AbiDetect found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1) and jetified-ffmpeg-kit-min-gpl-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-min-gpl:4.5.1-1)
     Duplicate class com.arthenica.ffmpegkit.AbstractSession found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1) and jetified-ffmpeg-kit-min-gpl-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-min-gpl:4.5.1-1)

**Comment by Shabad963** [comment]
Iam  already using audioplayer package in my project before , so after using this package these duplicate errors are coming.hope u help me with this

**Comment by shabaad** [comment]
Iam already using audioplayer package in my project before , so after using this package these duplicate errors are coming.hope u help can me with this
